from django.shortcuts import render, get_object_or_404

PROJECTS = [
    {
        'slug': 'studyai',
        'title': 'StudyAI',
        'tagline': 'AI-powered study assistant with autonomous agents',
        'date': 'Mar 2026',
        'github': 'https://github.com/devyansh770-hue/AIStudyAssistant',
        'tags': ['Python', 'Django', 'Gemini API', 'SQLite', 'REST APIs'],
        'color': '#00f5d4',
        'icon': '🎓',
        'highlights': [
            'Architected a production-ready Django backend with a modular 5-app system and 9 relational models for scalable RESTful API design.',
            'Developed 3 autonomous AI agents — Quiz Generation, Schedule Advisor, and Tutor — leveraging Google Gemini API for structured, logic-driven outputs.',
            'Engineered a 5-layer security pipeline: OTP email verification, rate limiting, brute force protection, session management, and CSRF.',
        ],
        'problem': 'Students struggle with personalized study planning and self-assessment at scale.',
        'solution': "Autonomous AI agents that adapt to each student's pace, generating quizzes, schedules, and tutoring sessions on demand.",
        'impact': 'Production-ready system with enterprise-grade security supporting concurrent multi-user sessions.',
    },
    {
        'slug': 'algodsa',
        'title': 'AlgoDSA',
        'tagline': 'Interactive DSA learning platform with live judge & visual walkthroughs',
        'date': 'Jul 2026 – Aug 2026',
        'github': 'https://github.com/devyansh770-hue/AlgoDSA',
        'live': 'https://algo-dsa-eight.vercel.app',
        'tags': ['HTML', 'CSS', 'JavaScript', 'Django', 'REST APIs', 'Vercel'],
        'color': '#00f5d4',
        'icon': '⚡',
        'highlights': [
            'Built an interactive DSA platform covering 50+ algorithm topics with step-by-step visual walkthroughs and an integrated code editor.',
            'Deployed on Vercel with a Django REST backend, achieving sub-200ms response times for live code evaluation.',
            'Implemented progress tracking and difficulty-based problem curation, increasing user retention by keeping learners on structured paths.',
        ],
        'problem': 'DSA learners lack platforms that combine visual explanations with immediate code execution feedback.',
        'solution': 'A full-stack platform with animated algorithm visualizations, a live judge, and structured topic pathways.',
        'impact': 'Live at algo-dsa-eight.vercel.app — actively used for competitive programming preparation.',
    },
    {
        'slug': 'shared-expenses-app',
        'title': 'Shared Expenses App',
        'tagline': 'Full-stack group expense tracker with smart settlement engine',
        'date': 'Jun 2026',
        'github': 'https://github.com/devyansh770-hue/shared-expenses-app',
        'live': 'https://shared-expenses-app-blue.vercel.app',
        'tags': ['Next.js', 'TypeScript', 'PostgreSQL', 'Prisma', 'Vercel'],
        'color': '#f72585',
        'icon': '💸',
        'highlights': [
            'Built a production-grade Next.js app with PostgreSQL and Prisma ORM supporting dynamic group memberships and real-time expense tracking.',
            'Engineered an anomaly-aware CSV import pipeline that detects and flags inconsistent entries before data ingestion.',
            'Implemented transparent balance calculations and a minimum-transaction settlement algorithm to resolve debts with the fewest transfers.',
        ],
        'problem': 'Group expense management tools either lack transparency in balance calculations or have cumbersome UX for settling up.',
        'solution': 'A Next.js + PostgreSQL full-stack app with automatic debt minimization, CSV import, and a clean settlement dashboard.',
        'impact': 'Live at shared-expenses-app-blue.vercel.app — supports multi-group, multi-member expense flows end-to-end.',
    },
    {
        'slug': 'investiq-ai',
        'title': 'InvestIQ AI',
        'tagline': 'AI-powered investment intelligence platform for retail investors',
        'date': 'Jun 2026',
        'github': 'https://github.com/devyansh770-hue/investiq-ai',
        'tags': ['TypeScript', 'Next.js', 'AI/ML', 'REST APIs'],
        'color': '#7b2fff',
        'icon': '📈',
        'highlights': [
            'Designed an AI-driven investment platform that aggregates financial data and surfaces actionable stock insights for retail investors.',
            'Built with TypeScript and Next.js for type-safe, performant rendering with server-side data fetching from financial APIs.',
            'Integrated AI summarization models to generate plain-language investment narratives from complex financial indicators.',
        ],
        'problem': 'Retail investors are overwhelmed by raw financial data and lack affordable, personalized investment guidance.',
        'solution': 'An AI layer that translates complex market signals into plain-language insights and portfolio recommendations.',
        'impact': 'Demonstrates applied AI in fintech — bridging the gap between data science and everyday investment decisions.',
    },
    {
        'slug': 'ai-resume-analyser',
        'title': 'AI Resume Analyser',
        'tagline': 'NLP-based resume-job description matching system',
        'date': 'Jan 2026 – Feb 2026',
        'github': 'https://github.com/devyansh770-hue',
        'tags': ['Python', 'Django', 'NLP', 'TF-IDF'],
        'color': '#f72585',
        'icon': '📄',
        'highlights': [
            'Developed an AI-based system to analyze resumes and match them with job descriptions using NLP techniques.',
            'Implemented keyword extraction and TF-IDF similarity scoring to evaluate resume relevance against job postings.',
            'Generated automated feedback to improve ATS compatibility and overall resume quality.',
        ],
        'problem': "Job seekers don't know why their resumes get filtered out by ATS systems.",
        'solution': 'NLP pipeline that scores resume-job fit and provides actionable improvement feedback.',
        'impact': 'Helps candidates optimize resumes before applying, increasing interview call rates.',
    },
    {
        'slug': 'arogyacheck',
        'title': 'ArogyaCheck',
        'tagline': 'Full-stack health screening for rural populations',
        'date': 'Feb 2026 – Mar 2026',
        'github': 'https://github.com/jyotsnak1603/arogyacheck',
        'tags': ['Python', 'Django', 'Plotly', 'Matplotlib', 'Bootstrap'],
        'color': '#7b2fff',
        'icon': '🏥',
        'highlights': [
            'Engineered a full-stack health screening platform with complex business logic for 3 distinct user roles, addressing preventive care gaps in rural areas.',
            'Built a Django predictive engine analyzing 15+ health parameters to identify risks for chronic diseases including diabetes and heart disease.',
            'Optimized backend architecture achieving an 80% reduction in load time (from 35s to 7s) — critical for low-bandwidth rural areas.',
        ],
        'problem': 'Rural populations lack access to preventive healthcare screening and early disease detection.',
        'solution': 'A low-bandwidth-optimized platform with predictive health analytics accessible to patients, doctors, and admins.',
        'impact': '80% load time reduction — from 35 seconds to just 7 seconds — making it viable in low-connectivity regions.',
    },
    {
        'slug': 'crime-incident-dashboard',
        'title': 'Crime Incident Analysis Dashboard',
        'tagline': 'Interactive Power BI dashboard for crime trend analytics',
        'date': 'Jan 2026',
        'github': 'https://github.com/devyansh770-hue/Crime-Incident-Analysis-Dashboard',
        'tags': ['Power BI', 'Data Analytics', 'Data Visualization', 'DAX'],
        'color': '#e63946',
        'icon': '🔍',
        'highlights': [
            'Built an interactive Power BI dashboard analyzing 100K+ crime incident records with time-series trend visualization.',
            'Delivered area-wise crime distribution maps, weapon usage heatmaps, and victim demographic breakdowns (age, gender, descent).',
            'Implemented custom DAX measures for rolling averages, YoY change rates, and crime severity scoring.',
        ],
        'problem': 'Raw crime incident data is too granular for public safety analysts to draw actionable conclusions quickly.',
        'solution': 'An interactive Power BI dashboard that condenses multi-dimensional crime data into navigable, filterable visual summaries.',
        'impact': 'Enables stakeholders to identify high-risk areas, peak crime periods, and demographic patterns at a glance.',
    },
    {
        'slug': 'research-publication-manager',
        'title': 'Research Publication Manager',
        'tagline': 'Centralized platform for faculty research workflows',
        'date': 'Jun 2025 – Jul 2025',
        'github': 'https://github.com/devyansh770-hue/Research-Publication-Manager',
        'tags': ['Python', 'Oracle DB', 'PL/SQL', 'Plotly', 'Streamlit'],
        'color': '#f77f00',
        'icon': '📚',
        'highlights': [
            'Engineered a centralized management platform to streamline research workflows for 100+ active faculty and student users.',
            'Architected a normalized Oracle database schema with 5+ tables and automated PL/SQL validation triggers.',
            'Reduced manual data entry errors by 85% while processing 500+ publication records.',
        ],
        'problem': 'University research teams used scattered spreadsheets causing data errors and lost publications.',
        'solution': 'Centralized Oracle-backed platform with automated PL/SQL validation ensuring data integrity.',
        'impact': '85% reduction in data entry errors across 500+ publication records for 100+ users.',
    },
    {
        'slug': 'leetcode-solutions',
        'title': 'LeetCode Solutions',
        'tagline': 'Curated C++ solutions with detailed complexity analysis',
        'date': 'Jun 2026 – Present',
        'github': 'https://github.com/devyansh770-hue/leetcode-solution',
        'tags': ['C++', 'Data Structures', 'Algorithms', 'Competitive Programming'],
        'color': '#f77f00',
        'icon': '🧠',
        'highlights': [
            'Actively maintained repository of 100+ LeetCode problems solved in optimized C++ with O(n) and O(log n) solutions preferred.',
            'Each solution includes time/space complexity analysis and multiple approaches from brute-force to optimal.',
            'Covers core DSA topics: dynamic programming, graph algorithms, binary search, sliding window, and backtracking.',
        ],
        'problem': 'Building and demonstrating consistent algorithmic problem-solving skills for technical interviews.',
        'solution': 'A structured, publicly documented problem-solving journal in C++ with clean code and annotated approaches.',
        'impact': 'Demonstrates disciplined DSA practice — updated weekly with new solutions as of Aug 2026.',
    },
]


def project_list(request):
    return render(request, 'projects/list.html', {'projects': PROJECTS})


def project_detail(request, slug):
    project = next((p for p in PROJECTS if p['slug'] == slug), None)
    if not project:
        from django.http import Http404
        raise Http404("Project not found")
    return render(request, 'projects/detail.html', {'project': project})
